name: GIT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PASSWORD }} 
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git checkout main
            git reset --hard HEAD
            git pull
            ${{ secrets.BUILD }}
            docker-compose up -d